### ISSUE TITLE
How to restructure URIs and provide proper redirects

### ISSUE THREAD

**Issue by vog** [ioccc-src/winner#13]
I noticed the following Twitter thread:

> "sounds like a good improvement in consistency, but can you please make the web server return redirects from the old URLs to the new ones?"
> [...]
> "yeah the clutter is annoying; i prefer to set my sites up so that i can keep redirects around forever without too much effort"

* https://twitter.com/fanf/status/1486075488330256390?cxt=HHwWjMC49Y7yzJ8pAAAA

and would like to trigger a structured discussion and proper decision making around this. We have currently 3 design decisions, made by different people/organizations, any 2 of which would have been fine, but all 3 in combination cause an issue:

1. IOCCC is using "GitHub Pages" to host the IOCCC website.
2. IOCCC wants to restructure its URIs.
3. "GitHub Pages" does not support proper HTTP redirects.

This issue is an anti-pattern in general (see [Cool URIs don't change](https://www.w3.org/Provider/Style/URI)), and especially problematic for past winners of the affected time range (see above Twitter thread).

On the positive side, each of the above design decisions provides an opportunity to fix this issue, only one of which needs to be applied to fix the whole issue:

1. IOCCC could stick to GitHub, but host their website somewhere else.
   * Any cheap website hosting would do, as the regular upload could be done e.g. by some TravisCI trigger purely using standard, free-of-charge GitHub functionality.
   * In my country (Germany), for instance, you'll get web hosting, including domain costs, for 1.90 € / month, which equals roughly 2.14 $ / month. It might be interesting to compare this with the current pure-domain costs of the ioccc.org domain.
   * Alternatively, a dead-simple "pull" mechanism via cronjob could be used, requiring a slightly more costly web hosting of about 4 to 5 € / month (i.e. roughly 4 to 5 $ / month).
2. IOCCC could stick to their old URI scheme.
   * This is a serious option and not necessarily as bad as it sounds.
   * As more and more of ioccc.org is generated automatically, this would just mean to add one or two special cases to the helper functions that generate the links.
   * In the end, we are all programmers here, aren't we? We usually adapt to way more complex system/compiler/language constraints. Compared to those, this new constraint (i.e. to keep all pre-existing URIs stable) looks like a rather simple and low-complexity constraint.
3. GitHub could be convinced to support proper HTTP redirects.
   * So far they didn't do anything in that direction, which is fine for new projects, but is a major obstacle for practically all pre-existing websites that want to use "GitHub Pages". Maybe GitHub changes their mind if they are approached by a well-known organization with a long history and high reputation like the IOCCC?
   * While it is understandable that "GitHub Pages" doesn't provide full ".htaccess" support, or any other scripting language for that matter, supporting a simple special file such as ".gh_pages/legacy_mappings", containing just lines of "OLD_PATH NEW_URI" pairs, should be feasible even from a performance and scalability point of view.
   * Maybe an additional redirect code (301, 303 or 307) would be nice, but even if they decided to hard-code one redirect type for all redirects, it would still be a huge step forward.

I feel neither entitled nor motivated to discuss the merits or pitfalls of each solution, as I'm neither personally affected by this issue, nor am I in any decision making position, neither at IOCCC nor at GitHub. I just feel like this discussion needs some proper seeding, and this is my attempt to contribute exactly that.

**Comment by lcn2** [comment]
While we appreciate the spirit and effort you put into your suggestions, @vog:

1. The demand to download the winners are released is enormous (**HUGE**).  Hosting sites that charge extra the excess bandwidth would be very costly.  Hosting sites that put a bandwidth cap on the site would block access soon after winners are announced.  And those who claim 'unlimited' service would likely fall over from the load even if we could afford a high bandwidth hosting service.  GitHub is allowing the IOCCC to host the site for free and has the server, network and load balancing infrastructure to handle the load.

2. We need to move 1988 they 2004 to deal with how we are managing the new site.   Our requirements push us into the model of 1-directory per winner.

3. It would be nice of GitHub did this, but it is not their model it seems.

We will use META tags to redirect the prog.c and hint files for a period of time to help.

Sorry.

**Comment by vog** [comment]
Thanks for considering the options and for explaining the drawbacks as well as your final solution so clearly. This is much appreciated and exactly what I was aiming for. Thus, I see my main goal achieved. Having this all documented long-term here in the issue tracker is in my point of view a huge improvement over partial bits of explanation in some Twitter thread that may disappear at any time.

One final question: I'm very curious to see "**HUGE**" being quantified, e.g. in peak TB / hour or similar. Are you willing to share these numbers, or would that be in violation of question 1 and 2 of [the FAQ](https://www.ioccc.org/faq.html)?

**Comment by lcn2** [comment]
We have seen peak web site new session rates at hundreds of new sessions per second, @vog.  Sometimes referred to as the "**/.** effect": a mention in a popular tech forum resulting in lots of people rushing to see the news.

A fair fraction of those new sessions look around the site when the IOCCC winners are announced and end up downloading a source compressed tarball (either all the winners or for most recent compressed tarball), which is larger than your typical web page.  To keep the web site responsive requires a distributed server farm, good routers, plenty of bandwidth, file content caching, load balancing, distributed DNS, plus "other" things that we prefer to keep private.

BTW: We DO plan to move / break the links to the compressed tarballs as we are going to change the compression format to reduce bandwidth a bit.  We won't do a META tar redirect because the fundamental filename extension / file type is changing.

The GitHub server farm is designed to handle such loads.

**Comment by lcn2** [comment]
On a side note:

While we appreciate the spirit of the [Cool URIs don't change](https://www.w3.org/Provider/Style/URI) article, and we really try to avoid changing URLs on our web site, we find the dismissive zeal of that author gets in the way of an otherwise important message.  

> BTW: URIs exist in a namespace.  As such **URIs NEVER change**: no more than the number 2 that exists on the real number line (R) and never changes in R.

However a web server response to a **URL DOES AND  WILL change**: say due temporary or permanent server error or when the content behind the URI / URL changes.

When the content behind a URL must CHANGE, sometimes the URL no longer serves its purpose and so the web server response MUST change.  And while response is a bit pedantic and nit-picky, it does speak to some of the fallacies expressed by that author.   We strongly prefer to **NOT** make URLs people depend result in web server errors.  We also fundamentally reject the "not cool" label of that document author places on web server URLs that MUST result in a web server response change, including _document not found 404 errors_.

We do **NOT** want debate that document here.  This is not that place.   We only mentioned this because you raised the issue in more than one forum and we thought deserved a specific response to the ** Cool URIs don't change** document.  Nevertheless we ask you do not debate the topic of  the ** Cool URIs don't change** document here if you please.

BTW: Every IOCCC winning entry will have some amount of content change.  Most winners won't need a URL change, but some will.  And we plan to liter our file tree with META tag redirected for a period of time before people get used to the new locations.  In some cases we will **NOT** forward, but all of the important cases we will for a reasonable period of time.

Thank you again @vog for expressing your concerns.  We hope we can move on from this topic so we can return to focusing on the multi-thousand hour project to retool how the IOCCC is run.
